base: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color

icons:
  Manual: Proxy.png
  Auto: Auto.png
  Fallback: Available.png
  United States: United_States.png
  Japan: Japan.png
  Hong Kong: Hong_Kong.png
  Taiwan: Taiwan.png
  Singapore: Singapore.png
  South Korea: Korea.png
  AI: AI.png
  Apple: Apple.png
  Microsoft: Microsoft.png
  Google: Google.png
  Developer: GitHub.png
  Telegram: Telegram.png
  Social: Twitter.png
  YouTube: YouTube.png
  TikTok: TikTok.png
  Streaming: Streaming.png
  Emby: Emby.png
  Gaming: Game.png
  Brokerage: PayPal.png
  Schwab: Global.png
  Crypto: Cryptocurrency.png
  Final: Final.png

