base: https://raw.githubusercontent.com/wenjinliuu/Lane/main/assets/icons

icons:
  Manual: third-party/qure/Proxy.png
  AI: third-party/qure/AI.png
  Brokerage: third-party/qure/Magic.png
  Crypto: third-party/qure/Cryptocurrency_3.png
  YouTube: third-party/qure/YouTube.png
  TikTok: third-party/qure/TikTok.png
  Emby: third-party/qure/Emby.png
  Streaming: third-party/qure/Netflix.png
  Gaming: third-party/qure/Steam.png
  Telegram: third-party/qure/Telegram.png
  Social: third-party/qure/X.png
  Developer: third-party/qure/GitHub.png
  Google: third-party/qure/Google_Search.png
  Microsoft: third-party/qure/Microsoft.png
  Apple: third-party/qure/Apple_1.png
  Final: third-party/qure/Global.png
  US Auto: third-party/qure/United_States.png
  US Manual: third-party/qure/United_States.png
  JP Auto: third-party/qure/Japan.png
  JP Manual: third-party/qure/Japan.png
  HK Auto: third-party/qure/Hong_Kong.png
  HK Manual: third-party/qure/Hong_Kong.png
  TW Auto: third-party/qure/China.png
  TW Manual: third-party/qure/China.png
  SG Auto: third-party/qure/Singapore.png
  SG Manual: third-party/qure/Singapore.png
