base: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color

icons:
  Manual: Proxy.png
  United States: United_States.png
  Japan: Japan.png
  Hong Kong: Hong_Kong.png
  Taiwan: Taiwan.png
  Singapore: Singapore.png
  AI: AI.png
  Apple: Apple.png
  Microsoft: Microsoft.png
  Google: Google_Search.png
  Developer: GitHub.png
  Telegram: Telegram.png
  Social: X.png
  YouTube: YouTube.png
  TikTok: TikTok.png
  Streaming: ForeignMedia.png
  Emby: Emby.png
  Gaming: Steam.png
  Brokerage: Magic.png
  Schwab: SSID_1.png
  Crypto: Cryptocurrency_3.png
  Final: Final.png
