from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

import yaml

from .compiler import CompiledRuleset
from .filters import build_filters
from .model import Rule


CONFIG_FILENAMES = {
    "stash": "Lane_stash.yaml",
    "loon": "Lane_loon.conf",
    "shadowrocket": "Lane_shadowrocket.conf",
    "surge": "Lane_surge.conf",
    "qx": "Lane_qx.conf",
    "egern": "Lane_egern.yaml",
}
TARGETS = tuple(CONFIG_FILENAMES)
RULES_DIR = "rules"
STASH_BEHAVIOR_ORDER = ("domain", "ipcidr", "classical")
GENERATED_HEADER = "# Generated by Lane. Do not edit generated rule files.\n"
PROFILE_HEADER = "# Lane | Local profile template\n"
SUBSCRIPTION_PLACEHOLDER = "你的订阅地址"
STASH_PROVIDER_NAME = "Subscription1"
MULTICAST_EXCLUDED_ROUTES = (
    "224.0.0.0/4",
    "239.255.255.250/32",
    "ff02::fb/128",
)
# Surge rejects an IPv6 entry here ("Invalid excluded route: ff02::fb/128") and QX
# only documents IPv4 ranges, so both get the IPv4 subset. Shadowrocket documents
# the IPv6 form and Loon/Egern take the full list.
IPV4_EXCLUDED_ROUTES = tuple(
    route for route in MULTICAST_EXCLUDED_ROUTES if ":" not in route
)
REAL_IP_DOMAINS = (
    "*.stun.*.*",
    "*.stun.*.*.*",
    "*.stun.*.*.*.*",
    "*.stun.*.*.*.*.*",
    "*.n.n.srv.nintendo.net",
    "*.stun.playstation.net",
    "xbox.*.*.microsoft.com",
    "*.*.xboxlive.com",
    "*.msftncsi.com",
    "*.msftconnecttest.com",
    "*.lan",
    "*.local",
)
# Stash documents the leading ``+.`` form for suffix-style fake-IP exclusions.
STASH_REAL_IP_DOMAINS = (
    "+.stun.*.*",
    "+.stun.*.*.*",
    "+.stun.*.*.*.*",
    "+.stun.*.*.*.*.*",
    "*.n.n.srv.nintendo.net",
    "+.stun.playstation.net",
    "xbox.*.*.microsoft.com",
    "*.*.xboxlive.com",
    "*.msftncsi.com",
    "*.msftconnecttest.com",
    "*.lan",
    "*.local",
)
HIJACK_DNS_SERVERS = ("8.8.8.8:53", "8.8.4.4:53")
# Shadowrocket ships a built-in PROXY policy that follows the node picked on the
# home screen, so the profile references it instead of defining a Manual group.
SHADOWROCKET_MANUAL_POLICY = "PROXY"
LOCAL_PROFILE_NOTICE = (
    "# Lane 不提供节点；导入启用前，将你的订阅地址替换为本客户端支持的完整订阅链接。\n"
    "# 建议复制/保存为本地配置，不跟随远程整份更新；节点与远程规则仍独立更新。\n"
    "# 换用新版完整配置前，请备份并重新填入订阅地址及个人修改。\n"
)
SERVICE_GROUP_NOTICE = (
    "# Brokerage：富途/Moomoo 保留域名与 IP 覆盖；老虎、长桥仅保留实测关键域名；嘉信规则并入本组。\n"
    "# Crypto：仅 Binance、OKX、Bybit、Bitget；当前网络可正常访问时，可手动选择 DIRECT。\n"
    "# 上述两组默认均为 Manual；分流只控制网络路径，不保证入金或交易结果。\n"
    "# AppleCN：命中苹果大陆服务名单时优先 DIRECT，其他 Apple 服务仍走 Apple 策略组。\n"
    "# Google 不再有大陆直连例外名单，全部域名统一走 Google 策略组。\n"
    "# LAN：私有网段与本地域名直连，位于全部规则之前，带 no-resolve。\n"
    "# China：已知中国域名先直连；General Proxy 随后保护已知境外域名，避免被后续 IP 判断误导。\n"
    "# General Proxy 策略同为 Final，不是另一个出口；它仍位于业务 IP / CN IP / GEOIP 之前。\n"
    "# CN IP：gaoyifan IPv4+IPv6 五次三次共识窗直连兜底，位于精细规则之后、GEOIP / Final 之前。\n"
)
EGERN_RULE_FIELDS = {
    "full": "domain_set", "domain": "domain_suffix_set",
    "keyword": "domain_keyword_set", "regexp": "domain_regex_set",
    "ipcidr": "ip_cidr_set", "ipcidr6": "ip_cidr6_set",
}
CLIENT_NOTES = {
    "stash": (
        "Domain and CIDR payloads use specialized rule-provider behaviors; "
        "DOMAIN-REGEX and other non-specialized rules remain classical."
    ),
    "loon": (
        "DOMAIN-REGEX is omitted because Loon remote rules do not support it. "
        "Remote filters intentionally leave their sources unpinned so local "
        "nodes and multiple subscriptions can be considered."
    ),
    "shadowrocket": (
        "DOMAIN-REGEX is omitted for compatibility. Service groups follow the "
        "built-in PROXY policy (the node picked on the home screen) instead of a "
        "generated Manual group; icons are omitted because Shadowrocket has no "
        "policy-group icon parameter."
    ),
    "surge": (
        "DOMAIN-REGEX is unsupported and omitted. Region automation uses native "
        "Smart groups over a hidden raw-node pool; visible groups carry icon-url."
    ),
    "qx": (
        "Native host/ip rules with explicit policies. DOMAIN-REGEX is omitted; "
        "Surge-style no-resolve is not emitted. QX uses native domain/IP "
        "matching priorities. System DNS is used by default, so no "
        "server = system entry is emitted. excluded_routes stays IPv4-only and "
        "the [server_remote] templates ship commented out, because QX rejects a "
        "profile whose resource entries are not valid addresses."
    ),
    "egern": (
        "Native YAML rule sets preserve domain regex and no_resolve. Requires a "
        "current Egern release with urls and flatten support."
    ),
}
UPDATE_TIME_PREFIX = "# Last updated: "
UPDATE_TIME_PATTERN = re.compile(r"^# Last updated: .*\n?", re.MULTILINE)
UPDATE_TIMEZONE = ZoneInfo("Asia/Shanghai")


def write_if_changed(path: Path, content: str) -> bool:
    """Write a UTF-8 text file only when its contents changed."""

    if not content.endswith("\n"):
        content += "\n"
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def write_json_if_changed(path: Path, value: Any) -> bool:
    return write_if_changed(
        path,
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
    )


def _without_update_time(content: str) -> str:
    return UPDATE_TIME_PATTERN.sub("", content, count=1)


def _with_stable_update_time(path: Path, content: str) -> str:
    """Add an update time, preserving the old one when generated content is unchanged."""

    if not content.endswith("\n"):
        content += "\n"
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if _without_update_time(existing) == _without_update_time(content):
            return existing

    timestamp = datetime.now(UPDATE_TIMEZONE).strftime(
        "%Y-%m-%d %H:%M:%S (Asia/Shanghai)"
    )
    first_line, remainder = content.split("\n", 1)
    return f"{first_line}\n{UPDATE_TIME_PREFIX}{timestamp}\n{remainder}"


def render_rule(
    rule: Rule, target: str, no_resolve: bool = False, policy: str = "Manual"
) -> str | None:
    kinds = {
        "full": "DOMAIN",
        "domain": "DOMAIN-SUFFIX",
        "keyword": "DOMAIN-KEYWORD",
        "regexp": "DOMAIN-REGEX",
        "ipcidr": "IP-CIDR",
        "ipcidr6": "IP-CIDR6",
    }
    if target not in TARGETS:
        raise ValueError(f"Unknown target: {target}")
    if target == "egern":
        raise ValueError("Egern rules must be rendered as a YAML rule set")
    if target == "qx":
        qx_kinds = {
            "full": "host", "domain": "host-suffix", "keyword": "host-keyword",
            "ipcidr": "ip-cidr", "ipcidr6": "ip6-cidr",
        }
        if rule.kind not in qx_kinds:
            return None
        # QX has its own IP matching semantics; do not emit Surge-only modifiers.
        return f"{qx_kinds[rule.kind]},{rule.value},{_qx_policy(policy)}"
    if rule.kind == "regexp" and target != "stash":
        return None
    if rule.kind not in kinds:
        return None
    parts = [kinds[rule.kind], rule.value]
    if no_resolve and rule.kind in {"ipcidr", "ipcidr6"}:
        parts.append("no-resolve")
    return ",".join(parts)


def stash_behavior(rule: Rule) -> str:
    if rule.kind in {"full", "domain"}:
        return "domain"
    if rule.kind in {"ipcidr", "ipcidr6"}:
        return "ipcidr"
    return "classical"


def stash_provider_id(rule_id: str, behavior: str) -> str:
    if behavior not in STASH_BEHAVIOR_ORDER:
        raise ValueError(f"Unknown Stash behavior: {behavior}")
    return f"{rule_id}-{behavior}"


def stash_provider_parts(
    ruleset: CompiledRuleset,
) -> tuple[tuple[str, tuple[Rule, ...]], ...]:
    grouped: dict[str, list[Rule]] = {
        behavior: [] for behavior in STASH_BEHAVIOR_ORDER
    }
    for rule in ruleset.rules:
        grouped[stash_behavior(rule)].append(rule)
    return tuple(
        (behavior, tuple(grouped[behavior]))
        for behavior in STASH_BEHAVIOR_ORDER
        if grouped[behavior]
    )


def render_stash_payload_rule(rule: Rule, behavior: str) -> str:
    actual = stash_behavior(rule)
    if actual != behavior:
        raise ValueError(
            f"Stash rule {rule.kind}:{rule.value} belongs to {actual}, not {behavior}"
        )
    if behavior == "domain":
        return rule.value if rule.kind == "full" else f"+.{rule.value}"
    if behavior == "ipcidr":
        return rule.value
    rendered = render_rule(rule, "stash")
    if rendered is None:
        raise ValueError(f"Unsupported Stash classical rule: {rule.kind}")
    return rendered


def _qx_policy(name: str) -> str:
    return "direct" if name == "DIRECT" else name


def rule_filename(target: str, rule_id: str) -> str:
    return f"{rule_id}.{'yaml' if target == 'egern' else 'list'}"


def _rule_url(
    project: dict[str, Any],
    target: str,
    rule_id: str,
    directory: str = RULES_DIR,
) -> str:
    return (f"{project['project']['raw_base'].rstrip('/')}/dist/{target}/{directory}/"
            f"{rule_filename(target, rule_id)}")


def _yaml(data: dict[str, Any]) -> str:
    return yaml.safe_dump(data, allow_unicode=True, sort_keys=False, width=4096)


def render_egern_ruleset(ruleset: CompiledRuleset) -> str:
    data: dict[str, Any] = {}
    if ruleset.no_resolve:
        data["no_resolve"] = True
    for rule in ruleset.rules:
        data.setdefault(EGERN_RULE_FIELDS[rule.kind], []).append(rule.value)
    return _ruleset_header(ruleset) + _yaml(data)


def _ruleset_header(ruleset: CompiledRuleset) -> str:
    return GENERATED_HEADER + "".join(f"# {notice}\n" for notice in ruleset.source_notices)


def _icon(icons: dict[str, Any], name: str) -> str | None:
    filename = icons.get("icons", {}).get(name)
    if not filename:
        return None
    return f"{icons['base'].rstrip('/')}/{filename}"


def _with_icon(group: dict[str, Any], icons: dict[str, Any], name: str) -> dict[str, Any]:
    if url := _icon(icons, name):
        group["icon"] = url
    return group


def _surge_icon(icons: dict[str, Any], name: str) -> str:
    url = _icon(icons, name)
    return f",icon-url={url}" if url else ""


def _region_auto_names(policies: dict[str, Any]) -> list[str]:
    return [region["auto_name"] for region in policies["regions"]]


def _stash_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    project_settings = project["project"]
    benchmark = project["benchmark"]
    update_settings = project["updates"]
    raw_base = project_settings["raw_base"].rstrip("/")
    filters = build_filters(policies)

    groups: list[dict[str, Any]] = []
    # Stash drops the explicit ``proxies`` entries of a group that also sets
    # ``include-all``, which hid the region Auto groups inside Manual. Naming the
    # provider with ``use`` keeps both the region groups and every node visible.
    groups.append(
        _with_icon(
            {
                "name": "Manual",
                "type": "select",
                "proxies": _region_auto_names(policies),
                "use": [STASH_PROVIDER_NAME],
            },
            icons,
            "Manual",
        )
    )

    for service in policies["service_groups"]:
        groups.append(
            _with_icon(
                {
                    "name": service,
                    "type": "select",
                    "proxies": list(policies["service_options"]),
                },
                icons,
                service,
            )
        )

    for region in policies["regions"]:
        region_filter = filters["regions"][region["name"]]
        groups.append(
            _with_icon(
                {
                    "name": region["auto_name"],
                    "type": "url-test",
                    "include-all": True,
                    "filter": region_filter,
                    "interval": benchmark["interval"],
                    "tolerance": benchmark["tolerance"],
                    "lazy": benchmark["lazy"],
                },
                icons,
                region["auto_name"],
            )
        )
        groups.append(
            _with_icon(
                {
                    "name": region["manual_name"],
                    "type": "select",
                    "include-all": True,
                    "filter": region_filter,
                },
                icons,
                region["manual_name"],
            )
        )

    providers: dict[str, dict[str, Any]] = {}
    route_rules: list[str] = []
    for entry in policies["_compiled_rulesets"]:
        for behavior, _ in stash_provider_parts(entry):
            provider_id = stash_provider_id(entry.id, behavior)
            providers[provider_id] = {
                "type": "http",
                "behavior": behavior,
                "format": "text",
                "url": (
                    f"{raw_base}/dist/stash/{RULES_DIR}/"
                    f"{provider_id}.list"
                ),
                "path": f"./rulesets/{provider_id}.list",
                "interval": update_settings["rule_interval"],
            }
            no_resolve = (
                ",no-resolve"
                if behavior == "ipcidr" and entry.no_resolve
                else ""
            )
            route_rules.append(
                f"RULE-SET,{provider_id},{entry.policy}{no_resolve}"
            )
    route_rules.extend(["GEOIP,CN,DIRECT", "MATCH,Final"])

    subscription = {
        "url": SUBSCRIPTION_PLACEHOLDER,
        "interval": update_settings["node_interval"],
        "benchmark-url": benchmark["url"],
        "benchmark-timeout": benchmark["timeout"],
    }
    data = {
        "mode": "rule",
        "log-level": "warning",
        "ipv6": False,
        "dns": {"fake-ip-filter": list(STASH_REAL_IP_DOMAINS)},
        "proxy-providers": {STASH_PROVIDER_NAME: subscription},
        "proxy-groups": groups,
        "rule-providers": providers,
        "rules": route_rules,
    }
    body = yaml.safe_dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        width=4096,
        default_flow_style=False,
    )
    body = body.replace(
        "proxy-providers:\n",
        "# 在下面的 url 填写 Stash / Clash 格式节点订阅；第一份默认启用。\nproxy-providers:\n",
        1,
    )
    optional_subscription = "".join(
        f"  # {line}\n" for line in _yaml({"Subscription2": subscription}).splitlines()
    )
    body = body.replace(
        "proxy-groups:\n",
        "  # 多订阅：取消下方 Subscription2 整块注释并填写；更多订阅复制整块、名称递增，保留缩进。\n"
        "  # 新增订阅后，把名称追加到 Manual 的 use 列表；地区组用 include-all 自动纳入，无需改动。\n"
        + optional_subscription
        + "\n# Base, service, and region strategy groups.\nproxy-groups:\n",
        1,
    )
    body = body.replace(
        "rule-providers:\n",
        "# Remote rule files generated from the shared manifest.\nrule-providers:\n",
        1,
    )
    body = body.replace(
        "rules:\n",
        "# Rules are evaluated from top to bottom.\nrules:\n",
        1,
    )
    return (
        PROFILE_HEADER
        + LOCAL_PROFILE_NOTICE
        + SERVICE_GROUP_NOTICE
        + "\n"
        + body
    )


def _loon_group(
    name: str,
    group_type: str,
    members: list[str],
    benchmark: dict[str, Any],
    icon_url: str | None,
    *,
    automated: bool = False,
) -> str:
    parts = [f"{name} = {group_type}", *members]
    if automated:
        parts.append(f"url = {benchmark['url']}")
        parts.append(f"interval = {benchmark['interval']}")
        if group_type == "url-test":
            parts.append(f"tolerance = {benchmark['tolerance']}")
    if icon_url:
        parts.append(f"img-url = {icon_url}")
    return ",".join(parts)


def _loon_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    raw_base = project["project"]["raw_base"].rstrip("/")
    filters = build_filters(policies)
    lines = [
        PROFILE_HEADER.rstrip(),
        LOCAL_PROFILE_NOTICE.rstrip(),
        SERVICE_GROUP_NOTICE.rstrip(),
        "",
        "[General]",
        "ip-mode = ipv4-only",
        "udp-fallback-mode = REJECT",
        "allow-wifi-access = false",
        f"bypass-tun = {', '.join(MULTICAST_EXCLUDED_ROUTES)}",
        f"real-ip = {', '.join(REAL_IP_DOMAINS)}",
        f"hijack-dns = {', '.join(HIJACK_DNS_SERVERS)}",
        f"proxy-test-url = {benchmark['url']}",
        f"test-timeout = {benchmark['timeout']}",
        "",
        "[Proxy]",
        "",
        "# 在下面填写 Loon 格式节点订阅；也可通过应用内节点页面添加。",
        "# 如重新导入远程配置，请选择保留节点/订阅，勿使用全部覆盖。",
        "# 节点与规则的定时更新请在应用的资源更新设置中开启。",
        "[Remote Proxy]",
        "# 第一份默认启用；多订阅取消第二行注释并填写，更多订阅复制该行、别名递增。",
        f"Subscription1 = {SUBSCRIPTION_PLACEHOLDER}",
        f"# Subscription2 = {SUBSCRIPTION_PLACEHOLDER}",
        "",
        "# Node and region filters.",
        "[Remote Filter]",
        f'Manual Nodes = NameRegex, FilterKey = "{filters["manual"]}"',
    ]
    for region in policies["regions"]:
        code = region["code"]
        region_filter = filters["regions"][region["name"]]
        lines.append(f'{code} Nodes = NameRegex, FilterKey = "{region_filter}"')

    lines.extend(["", "# Base, service, and region strategy groups.", "[Proxy Group]"])
    lines.append(
        _loon_group(
            "Manual",
            "select",
            [*_region_auto_names(policies), "Manual Nodes"],
            benchmark,
            _icon(icons, "Manual"),
        )
    )
    for service in policies["service_groups"]:
        lines.append(
            _loon_group(
                service,
                "select",
                list(policies["service_options"]),
                benchmark,
                _icon(icons, service),
            )
        )
    for region in policies["regions"]:
        code = region["code"]
        lines.append(
            _loon_group(
                region["auto_name"],
                "url-test",
                [f"{code} Nodes"],
                benchmark,
                _icon(icons, region["auto_name"]),
                automated=True,
            )
        )
        lines.append(
            _loon_group(
                region["manual_name"],
                "select",
                [f"{code} Nodes"],
                benchmark,
                _icon(icons, region["manual_name"]),
            )
        )

    lines.extend(["", "# Ordered remote routing rules.", "[Remote Rule]"])
    for entry in policies["_compiled_rulesets"]:
        url = f"{raw_base}/dist/loon/{RULES_DIR}/{entry.id}.list"
        lines.append(
            f"{url}, policy = {entry.policy}, tag = {entry.title}, enabled = true"
        )
    lines.extend(
        ["", "# Local fallback rules.", "[Rule]", "GEOIP,CN,DIRECT", "FINAL,Final"]
    )
    return "\n".join(lines) + "\n"


def shadowrocket_options(policies: dict[str, Any]) -> list[str]:
    """Service options for Shadowrocket, with the built-in PROXY policy for Manual."""

    return [
        SHADOWROCKET_MANUAL_POLICY if option == "Manual" else option
        for option in policies["service_options"]
    ]


def _shadowrocket_config(
    project: dict[str, Any], policies: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    raw_base = project["project"]["raw_base"].rstrip("/")
    filters = build_filters(policies)
    config_url = f"{raw_base}/dist/shadowrocket/{CONFIG_FILENAMES['shadowrocket']}"
    lines = [
        PROFILE_HEADER.rstrip(),
        SERVICE_GROUP_NOTICE.rstrip(),
        "",
        "[General]",
        "ipv6 = false",
        "udp-policy-not-supported-behaviour = REJECT",
        f"tun-excluded-routes = {', '.join(MULTICAST_EXCLUDED_ROUTES)}",
        f"always-real-ip = {', '.join(REAL_IP_DOMAINS)}",
        f"hijack-dns = {', '.join(HIJACK_DNS_SERVERS)}",
        f"proxy-test-url = {benchmark['url']}",
        f"test-timeout = {benchmark['timeout']}",
        "# Remote URL used to refresh this configuration.",
        f"update-url = {config_url}",
        "",
        "# Service and region strategy groups.",
        f"# Shadowrocket 用内置 {SHADOWROCKET_MANUAL_POLICY} 策略代表首页选中的节点，"
        "因此不再生成 Manual 组；服务组默认跟随首页选择。",
        "[Proxy Group]",
    ]
    members = ",".join(shadowrocket_options(policies))
    for service in policies["service_groups"]:
        lines.append(
            f"{service} = select,{members},"
            f"policy-select-name={SHADOWROCKET_MANUAL_POLICY}"
        )
    for region in policies["regions"]:
        region_filter = filters["regions"][region["name"]]
        lines.append(
            f"{region['auto_name']} = url-test,url={benchmark['url']},"
            f"interval={benchmark['interval']},tolerance={benchmark['tolerance']},"
            f"timeout={benchmark['timeout']},select=0,"
            f"policy-regex-filter={region_filter}"
        )
        lines.append(
            f"{region['manual_name']} = select,select=0,"
            f"policy-regex-filter={region_filter}"
        )

    lines.extend(["", "# Ordered remote rules; the first match wins.", "[Rule]"])
    for entry in policies["_compiled_rulesets"]:
        url = f"{raw_base}/dist/shadowrocket/{RULES_DIR}/{entry.id}.list"
        lines.append(f"RULE-SET,{url},{entry.policy}")
    lines.extend(["GEOIP,CN,DIRECT", "FINAL,Final"])
    return "\n".join(lines) + "\n"


def _surge_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    updates = project["updates"]
    filters = build_filters(policies)
    smart_names = [region["surge_smart_name"] for region in policies["regions"]]
    surge_options = ["Manual", "DIRECT"]
    for region in policies["regions"]:
        surge_options.extend([region["surge_smart_name"], region["manual_name"]])
    lines = [
        PROFILE_HEADER.rstrip(), LOCAL_PROFILE_NOTICE.rstrip(), SERVICE_GROUP_NOTICE.rstrip(), "",
        "[General]", "loglevel = notify", "ipv6 = false",
        "udp-policy-not-supported-behaviour = REJECT",
        "allow-wifi-access = false", "dns-server = system",
        f"tun-excluded-routes = {', '.join(IPV4_EXCLUDED_ROUTES)}",
        f"always-real-ip = {', '.join(REAL_IP_DOMAINS)}",
        f"hijack-dns = {', '.join(HIJACK_DNS_SERVERS)}",
        f"proxy-test-url = {benchmark['url']}",
        f"test-timeout = {benchmark['timeout']}", "", "[Proxy]", "",
        "[Proxy Group]",
        "# 在 policy-path 填写 Surge 格式节点订阅；第一份默认启用，订阅组在策略界面隐藏。",
        f"Subscription1 = select,policy-path={SUBSCRIPTION_PLACEHOLDER},"
        f"update-interval={updates['node_interval']},hidden=true",
        f"# Subscription2 = select,policy-path={SUBSCRIPTION_PLACEHOLDER},"
        f"update-interval={updates['node_interval']},hidden=true",
        "",
        '# 多订阅：取消 Subscription2 注释并填写，再将 Node Pool 引用改为 include-other-group="Subscription1,Subscription2"。',
        "# 更多订阅复制订阅行、名称递增，并逐一加入隐藏 Node Pool；它只汇总真实代理节点。",
        "Node Pool = select,include-other-group=Subscription1,include-all-proxies=true,hidden=true",
        "# Manual 可直接选择地区 Smart，也保留 Node Pool 展开的全部单节点。",
        f"Manual = select,{','.join(smart_names)},include-other-group=Node Pool"
        f"{_surge_icon(icons, 'Manual')}",
    ]
    # Surge iOS and Mac both read icon-url on a policy group; hidden groups skip it.
    for service in policies["service_groups"]:
        lines.append(
            f"{service} = select,{','.join(surge_options)}{_surge_icon(icons, service)}"
        )
    lines.append("# 地区组从隐藏 Node Pool 展开真实节点并正向筛选；不会与 Manual 形成循环。")
    for region in policies["regions"]:
        # policy-regex-filter must stay unquoted. Surge keeps the quotes as part of
        # the pattern, so a quoted filter matches no node and the group ends up
        # empty; Surge then closes anything routed to it immediately. The region
        # patterns contain no comma, so no quoting is needed to protect them.
        suffix = (
            "include-other-group=Node Pool,"
            f"policy-regex-filter={filters['regions'][region['name']]}"
        )
        # The Smart group reuses the region Auto icon; icons.yaml keys stay client neutral.
        lines.append(
            f"{region['surge_smart_name']} = smart,{suffix}"
            f"{_surge_icon(icons, region['auto_name'])}"
        )
        lines.append(
            f"{region['manual_name']} = select,{suffix}"
            f"{_surge_icon(icons, region['manual_name'])}"
        )
    lines.extend(["", "# Ordered remote routing rules.", "[Rule]"])
    for entry in policies["_compiled_rulesets"]:
        lines.append(f"RULE-SET,{_rule_url(project, 'surge', entry.id)},{entry.policy},"
                     f"update-interval={updates['rule_interval']}")
    lines.extend(["GEOIP,CN,DIRECT", "FINAL,Final"])
    # Lane routes on TCP/SNI and never reads decrypted traffic. Surge keeps its MitM
    # settings per profile, so state it explicitly: without this section an enabled
    # MitM switch carries over and closes the TLS handshake for every intercepted
    # host, which looks exactly like broken routing.
    lines.extend([
        "",
        "# Lane 不做 HTTPS 解密；显式关闭 MitM，避免沿用客户端里已有的开关和域名列表。",
        "[MITM]",
        "enable = false",
    ])
    return "\n".join(lines) + "\n"


def _qx_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    updates = project["updates"]
    filters = build_filters(policies)

    def icon(name: str) -> str:
        url = _icon(icons, name)
        return f", img-url={url}" if url else ""

    lines = [
        PROFILE_HEADER.rstrip(), LOCAL_PROFILE_NOTICE.rstrip(), SERVICE_GROUP_NOTICE.rstrip(),
        "# 订阅填写位置在下方 [server_remote]。", "",
        "[general]", f"server_check_url = {benchmark['url']}",
        f"server_check_timeout = {min(5000, benchmark['timeout'] * 1000)}",
        "fallback_udp_policy = reject",
        f"dns_exclusion_list = {', '.join(REAL_IP_DOMAINS)}",
        # QX documents excluded_routes with IPv4 ranges only.
        f"excluded_routes = {', '.join(IPV4_EXCLUDED_ROUTES)}",
        # QX's [dns] server takes resolver addresses only. The system resolvers
        # are used by default and are turned off with no-system, so there is no
        # `server = system` to write here.
        "", "[dns]", "no-ipv6", "",
        "[policy]", (
            f"static = Manual, {', '.join(_region_auto_names(policies))}, "
            f"server-tag-regex=.+{icon('Manual')}"
        ),
    ]
    options = ", ".join(_qx_policy(option) for option in policies["service_options"])
    for service in policies["service_groups"]:
        lines.append(f"static = {service}, {options}{icon(service)}")
    for region in policies["regions"]:
        expression = filters["regions"][region["name"]]
        lines.append(
            f"url-latency-benchmark = {region['auto_name']}, server-tag-regex={expression}, "
            f"check-interval={benchmark['interval']}, alive-checking=false, "
            f"tolerance={benchmark['tolerance']}{icon(region['auto_name'])}"
        )
        lines.append(f"static = {region['manual_name']}, server-tag-regex={expression}"
                     f"{icon(region['manual_name'])}")
    lines.extend([
        "", "[server_remote]",
        # QX validates every [server_remote] entry as a resource address, so the
        # placeholder ships commented out: an unedited profile imports cleanly.
        "# 取消下面第一行注释并把占位符换成 Quantumult X 格式节点订阅；也可直接在应用内添加订阅。",
        "# 多订阅：再取消第二行注释并填写；更多订阅复制该行并使用不同 tag。",
        f"# {SUBSCRIPTION_PLACEHOLDER}, tag=Subscription1, update-interval={updates['node_interval']}, enabled=true",
        f"# {SUBSCRIPTION_PLACEHOLDER}, tag=Subscription2, update-interval={updates['node_interval']}, enabled=true",
        "", "[server_local]", "", "[filter_remote]",
        "# 不导入客户端默认 CN/LAN 资源，避免抢先覆盖本项目的服务分流。",
    ])
    for entry in policies["_compiled_rulesets"]:
        lines.append(
            f"{_rule_url(project, 'qx', entry.id)}, tag={entry.id}, "
            f"force-policy={_qx_policy(entry.policy)}, update-interval={updates['rule_interval']}, "
            "enabled=true"
        )
    lines.extend(["", "[filter_local]", "geoip,cn,direct", "final,Final"])
    return "\n".join(lines) + "\n"


def _egern_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    updates = project["updates"]
    filters = build_filters(policies)
    subscription_urls = [SUBSCRIPTION_PLACEHOLDER]
    groups = [{"select": {
        "name": "Node Pool", "urls": subscription_urls,
        "update_interval": updates["node_interval"], "hidden": True,
    }}]
    groups.append({"select": _with_icon({
        "name": "Manual", "policies": _region_auto_names(policies),
        "urls": subscription_urls,
        "update_interval": updates["node_interval"],
    }, icons, "Manual")})
    for service in policies["service_groups"]:
        groups.append({"select": _with_icon({
            "name": service, "policies": list(policies["service_options"]),
        }, icons, service)})
    for region in policies["regions"]:
        for kind, name in (("auto_test", region["auto_name"]), ("select", region["manual_name"])):
            group = {
                "name": name, "policies": ["Node Pool"], "flatten": True,
                "filter": filters["regions"][region["name"]],
            }
            if kind == "auto_test":
                group.update(interval=benchmark["interval"], tolerance=benchmark["tolerance"],
                             timeout=benchmark["timeout"])
            groups.append({kind: _with_icon(group, icons, name)})
    rules = [{"rule_set": {
        "match": _rule_url(project, "egern", entry.id), "policy": entry.policy,
        "update_interval": updates["rule_interval"],
    }} for entry in policies["_compiled_rulesets"]]
    rules.extend([{"geoip": {"match": "CN", "policy": "DIRECT"}},
                  {"default": {"policy": "Final"}}])
    data = {
        "ipv6": False, "allow_external_connections": False,
        "real_ip_domains": list(REAL_IP_DOMAINS),
        "hijack_dns": list(HIJACK_DNS_SERVERS),
        "vif_excluded_routes": list(MULTICAST_EXCLUDED_ROUTES),
        "proxy_latency_test_url": benchmark["url"],
        "dns": {"bootstrap": ["system"],
                "forward": [{"wildcard": {"match": "*", "value": "bootstrap"}}]},
        "policy_groups": groups, "rules": rules,
    }
    body = _yaml(data).replace(
        "policy_groups:\n",
        "# 在隐藏 Node Pool 的 urls 中填写 Egern 节点订阅；Manual 与地区组共享该来源。\n"
        "policy_groups:\n",
        1,
    )
    body = body.replace(
        f"    - {SUBSCRIPTION_PLACEHOLDER}\n",
        f"    - {SUBSCRIPTION_PLACEHOLDER}\n"
        "    # 多订阅：取消下一行注释并填写；更多地址在 urls 中逐行追加，保留缩进。\n"
        f"    # - {SUBSCRIPTION_PLACEHOLDER}\n",
        1,
    )
    return PROFILE_HEADER + LOCAL_PROFILE_NOTICE + SERVICE_GROUP_NOTICE + "\n" + body


def render_all(
    root: Path,
    project: dict[str, Any],
    policies: dict[str, Any],
    icons: dict[str, Any],
    rulesets: list[CompiledRuleset],
) -> dict[str, Any]:
    dist = root / "dist"
    render_policies = dict(policies)
    render_policies["_compiled_rulesets"] = rulesets
    skipped: dict[str, dict[str, int]] = {target: {} for target in TARGETS}
    expected: dict[str, set[Path]] = {target: set() for target in TARGETS}
    for target in TARGETS:
        for ruleset in rulesets:
            rendered: list[str] = []
            skipped_count = 0
            if target == "egern":
                content = render_egern_ruleset(ruleset)
            else:
                for rule in ruleset.rules:
                    line = render_rule(rule, target, ruleset.no_resolve, ruleset.policy)
                    if line is None:
                        skipped_count += 1
                    else:
                        rendered.append(line)
                content = _ruleset_header(ruleset) + "\n".join(rendered) + "\n"
            path = dist / target / RULES_DIR / rule_filename(target, ruleset.id)
            expected[target].add(path)
            write_if_changed(path, content)
            if target == "stash":
                for behavior, behavior_rules in stash_provider_parts(ruleset):
                    provider_id = stash_provider_id(ruleset.id, behavior)
                    provider_content = _ruleset_header(ruleset) + "\n".join(
                        render_stash_payload_rule(rule, behavior)
                        for rule in behavior_rules
                    ) + "\n"
                    provider_path = (
                        dist / target / RULES_DIR / f"{provider_id}.list"
                    )
                    expected[target].add(provider_path)
                    write_if_changed(provider_path, provider_content)
            if skipped_count:
                skipped[target][ruleset.id] = skipped_count

        rules_dir = dist / target / RULES_DIR
        if rules_dir.exists():
            for stale in rules_dir.iterdir():
                if not stale.is_file() or stale.suffix not in {".list", ".yaml"}:
                    continue
                if stale not in expected[target]:
                    stale.unlink()

    # Migrate the generated tree to the single order-independent rule tier.
    # Remove only Lane-generated files and leave any unknown user file intact.
    for target in TARGETS:
        for legacy_name in ("rules-full", "rules-profile"):
            legacy = dist / target / legacy_name
            if not legacy.is_dir():
                continue
            for stale in legacy.iterdir():
                if not stale.is_file() or stale.suffix not in {".list", ".yaml"}:
                    continue
                try:
                    generated = stale.read_text(encoding="utf-8").startswith(
                        GENERATED_HEADER
                    )
                except (OSError, UnicodeError):
                    generated = False
                if generated:
                    stale.unlink()
            if not any(legacy.iterdir()):
                legacy.rmdir()

    renderers = {
        "stash": _stash_config, "loon": _loon_config, "surge": _surge_config,
        "qx": _qx_config, "egern": _egern_config,
    }
    for target in TARGETS:
        content = (_shadowrocket_config(project, render_policies) if target == "shadowrocket"
                   else renderers[target](project, render_policies, icons))
        path = dist / target / CONFIG_FILENAMES[target]
        write_if_changed(path, _with_stable_update_time(path, content))
    return {
        "schema": 3,
        "unsupported_rules": skipped,
        "notes": dict(CLIENT_NOTES),
    }
