from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

import yaml

from .compiler import CompiledRuleset
from .filters import build_filters
from .model import Rule


CONFIG_FILENAMES = {
    "stash": "Lane_stash.yaml",
    "loon": "Lane_loon.conf",
    "shadowrocket": "Lane_shadowrocket.conf",
    "surge": "Lane_surge.conf",
    "qx": "Lane_qx.conf",
    "egern": "Lane_egern.yaml",
}
TARGETS = tuple(CONFIG_FILENAMES)
GENERATED_HEADER = "# Generated by Lane. Do not edit generated rule files.\n"
PROFILE_HEADER = "# Lane | Local profile template\n"
SUBSCRIPTION_PLACEHOLDER = "你的订阅地址"
LOCAL_PROFILE_NOTICE = (
    "# Lane 不提供节点；导入启用前，将你的订阅地址替换为本客户端支持的完整订阅链接。\n"
    "# 建议复制/保存为本地配置，不跟随远程整份更新；节点与远程规则仍独立更新。\n"
    "# 换用新版完整配置前，请备份并重新填入订阅地址及个人修改。\n"
)
SERVICE_GROUP_NOTICE = (
    "# Brokerage：富途/Moomoo、老虎、长桥，统一分流登录、行情及入金/交易相关连接。\n"
    "# Crypto：仅 Binance、OKX、Bybit、Bitget；当前网络可正常访问时，可手动选择 DIRECT。\n"
    "# Schwab：嘉信独立分流，可单独选择 DIRECT 或代理。\n"
    "# 上述三组默认均为 Manual；分流只控制网络路径，不保证入金或交易结果。\n"
    "# AppleCN / GoogleCN：命中独立大陆服务名单时优先 DIRECT，其他服务仍按原策略组分流。\n"
    "# CN IP：Loyalsoldier IPv4+IPv6 直连兜底，位于精细规则之后、GEOIP / Final 之前。\n"
)
EGERN_RULE_FIELDS = {
    "full": "domain_set", "domain": "domain_suffix_set",
    "keyword": "domain_keyword_set", "regexp": "domain_regex_set",
    "ipcidr": "ip_cidr_set", "ipcidr6": "ip_cidr6_set",
}
UPDATE_TIME_PREFIX = "# Last updated: "
UPDATE_TIME_PATTERN = re.compile(r"^# Last updated: .*\n?", re.MULTILINE)
UPDATE_TIMEZONE = ZoneInfo("Asia/Shanghai")


def write_if_changed(path: Path, content: str) -> bool:
    """Write a UTF-8 text file only when its contents changed."""

    if not content.endswith("\n"):
        content += "\n"
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def write_json_if_changed(path: Path, value: Any) -> bool:
    return write_if_changed(
        path,
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
    )


def _without_update_time(content: str) -> str:
    return UPDATE_TIME_PATTERN.sub("", content, count=1)


def _with_stable_update_time(path: Path, content: str) -> str:
    """Add an update time, preserving the old one when generated content is unchanged."""

    if not content.endswith("\n"):
        content += "\n"
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if _without_update_time(existing) == _without_update_time(content):
            return existing

    timestamp = datetime.now(UPDATE_TIMEZONE).strftime(
        "%Y-%m-%d %H:%M:%S (Asia/Shanghai)"
    )
    first_line, remainder = content.split("\n", 1)
    return f"{first_line}\n{UPDATE_TIME_PREFIX}{timestamp}\n{remainder}"


def render_rule(
    rule: Rule, target: str, no_resolve: bool = False, policy: str = "Manual"
) -> str | None:
    kinds = {
        "full": "DOMAIN",
        "domain": "DOMAIN-SUFFIX",
        "keyword": "DOMAIN-KEYWORD",
        "regexp": "DOMAIN-REGEX",
        "ipcidr": "IP-CIDR",
        "ipcidr6": "IP-CIDR6",
    }
    if target not in TARGETS:
        raise ValueError(f"Unknown target: {target}")
    if target == "egern":
        raise ValueError("Egern rules must be rendered as a YAML rule set")
    if target == "qx":
        qx_kinds = {
            "full": "host", "domain": "host-suffix", "keyword": "host-keyword",
            "ipcidr": "ip-cidr", "ipcidr6": "ip6-cidr",
        }
        if rule.kind not in qx_kinds:
            return None
        # QX has its own IP matching semantics; do not emit Surge-only modifiers.
        return f"{qx_kinds[rule.kind]},{rule.value},{_qx_policy(policy)}"
    if rule.kind == "regexp" and target != "stash":
        return None
    if rule.kind not in kinds:
        return None
    parts = [kinds[rule.kind], rule.value]
    if no_resolve and rule.kind in {"ipcidr", "ipcidr6"}:
        parts.append("no-resolve")
    return ",".join(parts)


def _qx_policy(name: str) -> str:
    return "direct" if name == "DIRECT" else name


def rule_filename(target: str, rule_id: str) -> str:
    return f"{rule_id}.{'yaml' if target == 'egern' else 'list'}"


def _rule_url(project: dict[str, Any], target: str, rule_id: str) -> str:
    return (f"{project['project']['raw_base'].rstrip('/')}/dist/{target}/rules/"
            f"{rule_filename(target, rule_id)}")


def _yaml(data: dict[str, Any]) -> str:
    return yaml.safe_dump(data, allow_unicode=True, sort_keys=False, width=4096)


def render_egern_ruleset(ruleset: CompiledRuleset) -> str:
    data: dict[str, Any] = {}
    if ruleset.no_resolve:
        data["no_resolve"] = True
    for rule in ruleset.rules:
        data.setdefault(EGERN_RULE_FIELDS[rule.kind], []).append(rule.value)
    return _ruleset_header(ruleset) + _yaml(data)


def _ruleset_header(ruleset: CompiledRuleset) -> str:
    return GENERATED_HEADER + "".join(f"# {notice}\n" for notice in ruleset.source_notices)


def _icon(icons: dict[str, Any], name: str) -> str | None:
    filename = icons.get("icons", {}).get(name)
    if not filename:
        return None
    return f"{icons['base'].rstrip('/')}/{filename}"


def _with_icon(group: dict[str, Any], icons: dict[str, Any], name: str) -> dict[str, Any]:
    if url := _icon(icons, name):
        group["icon"] = url
    return group


def _stash_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    project_settings = project["project"]
    benchmark = project["benchmark"]
    update_settings = project["updates"]
    raw_base = project_settings["raw_base"].rstrip("/")
    filters = build_filters(policies)

    groups: list[dict[str, Any]] = []
    groups.append(
        _with_icon(
            {
                "name": "Manual",
                "type": "select",
                "include-all": True,
            },
            icons,
            "Manual",
        )
    )

    for service in policies["service_groups"]:
        groups.append(
            _with_icon(
                {
                    "name": service,
                    "type": "select",
                    "proxies": list(policies["service_options"]),
                },
                icons,
                service,
            )
        )

    for region in policies["regions"]:
        region_filter = filters["regions"][region["name"]]
        groups.append(
            _with_icon(
                {
                    "name": region["auto_name"],
                    "type": "url-test",
                    "include-all": True,
                    "filter": region_filter,
                    "interval": benchmark["interval"],
                    "tolerance": benchmark["tolerance"],
                    "lazy": benchmark["lazy"],
                },
                icons,
                region["name"],
            )
        )
        groups.append(
            _with_icon(
                {
                    "name": region["manual_name"],
                    "type": "select",
                    "include-all": True,
                    "filter": region_filter,
                },
                icons,
                region["name"],
            )
        )

    providers: dict[str, dict[str, Any]] = {}
    route_rules: list[str] = []
    for entry in policies["_compiled_rulesets"]:
        providers[entry.id] = {
            "type": "http",
            "behavior": "classical",
            "format": "text",
            "url": f"{raw_base}/dist/stash/rules/{entry.id}.list",
            "path": f"./rulesets/{entry.id}.list",
            "interval": update_settings["rule_interval"],
        }
        route_rules.append(f"RULE-SET,{entry.id},{entry.policy}")
    route_rules.extend(["GEOIP,CN,DIRECT", "MATCH,Final"])

    subscription = {
        "url": SUBSCRIPTION_PLACEHOLDER,
        "interval": update_settings["node_interval"],
        "benchmark-url": benchmark["url"],
        "benchmark-timeout": benchmark["timeout"],
    }
    data = {
        "mode": "rule",
        "log-level": "warning",
        "ipv6": False,
        "proxy-providers": {"Subscription1": subscription},
        "proxy-groups": groups,
        "rule-providers": providers,
        "rules": route_rules,
    }
    body = yaml.safe_dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        width=4096,
        default_flow_style=False,
    )
    body = body.replace(
        "proxy-providers:\n",
        "# 在下面的 url 填写 Stash / Clash 格式节点订阅；第一份默认启用。\nproxy-providers:\n",
        1,
    )
    optional_subscription = "".join(
        f"  # {line}\n" for line in _yaml({"Subscription2": subscription}).splitlines()
    )
    body = body.replace(
        "proxy-groups:\n",
        "  # 多订阅：取消下方 Subscription2 整块注释并填写；更多订阅复制整块、名称递增，保留缩进。\n"
        + optional_subscription
        + "\n# Base, service, and region strategy groups.\nproxy-groups:\n",
        1,
    )
    body = body.replace(
        "rule-providers:\n",
        "# Remote rule files generated from the shared manifest.\nrule-providers:\n",
        1,
    )
    body = body.replace(
        "rules:\n",
        "# Rules are evaluated from top to bottom.\nrules:\n",
        1,
    )
    return (
        PROFILE_HEADER
        + LOCAL_PROFILE_NOTICE
        + SERVICE_GROUP_NOTICE
        + "\n"
        + body
    )


def _loon_group(
    name: str,
    group_type: str,
    members: list[str],
    benchmark: dict[str, Any],
    icon_url: str | None,
    *,
    automated: bool = False,
) -> str:
    parts = [f"{name} = {group_type}", *members]
    if automated:
        parts.append(f"url = {benchmark['url']}")
        parts.append(f"interval = {benchmark['interval']}")
        if group_type == "url-test":
            parts.append(f"tolerance = {benchmark['tolerance']}")
    if icon_url:
        parts.append(f"img-url = {icon_url}")
    return ",".join(parts)


def _loon_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    raw_base = project["project"]["raw_base"].rstrip("/")
    filters = build_filters(policies)
    lines = [
        PROFILE_HEADER.rstrip(),
        LOCAL_PROFILE_NOTICE.rstrip(),
        SERVICE_GROUP_NOTICE.rstrip(),
        "",
        "[General]",
        "ipv6 = false",
        "allow-wifi-access = false",
        f"proxy-test-url = {benchmark['url']}",
        f"test-timeout = {benchmark['timeout']}",
        "",
        "[Proxy]",
        "",
        "# 在下面填写 Loon 格式节点订阅；也可通过应用内节点页面添加。",
        "# 如重新导入远程配置，请选择保留节点/订阅，勿使用全部覆盖。",
        "# 节点与规则的定时更新请在应用的资源更新设置中开启。",
        "[Remote Proxy]",
        "# 第一份默认启用；多订阅取消第二行注释并填写，更多订阅复制该行、别名递增。",
        f"Subscription1 = {SUBSCRIPTION_PLACEHOLDER}",
        f"# Subscription2 = {SUBSCRIPTION_PLACEHOLDER}",
        "",
        "# Node and region filters.",
        "[Remote Filter]",
        f'Manual Nodes = NameRegex, FilterKey = "{filters["manual"]}"',
    ]
    for region in policies["regions"]:
        code = region["code"]
        region_filter = filters["regions"][region["name"]]
        lines.append(f'{code} Nodes = NameRegex, FilterKey = "{region_filter}"')

    lines.extend(["", "# Base, service, and region strategy groups.", "[Proxy Group]"])
    lines.append(
        _loon_group(
            "Manual",
            "select",
            ["Manual Nodes"],
            benchmark,
            _icon(icons, "Manual"),
        )
    )
    for service in policies["service_groups"]:
        lines.append(
            _loon_group(
                service,
                "select",
                list(policies["service_options"]),
                benchmark,
                _icon(icons, service),
            )
        )
    for region in policies["regions"]:
        code = region["code"]
        lines.append(
            _loon_group(
                region["auto_name"],
                "url-test",
                [f"{code} Nodes"],
                benchmark,
                _icon(icons, region["name"]),
                automated=True,
            )
        )
        lines.append(
            _loon_group(
                region["manual_name"],
                "select",
                [f"{code} Nodes"],
                benchmark,
                _icon(icons, region["name"]),
            )
        )

    lines.extend(["", "# Ordered remote routing rules.", "[Remote Rule]"])
    for entry in policies["_compiled_rulesets"]:
        url = f"{raw_base}/dist/loon/rules/{entry.id}.list"
        lines.append(
            f"{url}, policy = {entry.policy}, tag = {entry.title}, enabled = true"
        )
    lines.extend(
        ["", "# Local fallback rules.", "[Rule]", "GEOIP,CN,DIRECT", "FINAL,Final"]
    )
    return "\n".join(lines) + "\n"


def _shadowrocket_config(
    project: dict[str, Any], policies: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    raw_base = project["project"]["raw_base"].rstrip("/")
    filters = build_filters(policies)
    config_url = f"{raw_base}/dist/shadowrocket/{CONFIG_FILENAMES['shadowrocket']}"
    lines = [
        PROFILE_HEADER.rstrip(),
        SERVICE_GROUP_NOTICE.rstrip(),
        "",
        "[General]",
        "ipv6 = false",
        f"proxy-test-url = {benchmark['url']}",
        f"test-timeout = {benchmark['timeout']}",
        "# Remote URL used to refresh this configuration.",
        f"update-url = {config_url}",
        "",
        "# Base, service, and region strategy groups.",
        "[Proxy Group]",
        (
            "Manual = select,"
            f"url={benchmark['url']},interval={benchmark['interval']},"
            f"timeout={benchmark['timeout']},select=0,"
            f"policy-regex-filter={filters['manual']}"
        ),
    ]
    for service in policies["service_groups"]:
        members = ",".join(policies["service_options"])
        lines.append(
            f"{service} = select,{members},url={benchmark['url']},"
            f"interval={benchmark['interval']},timeout={benchmark['timeout']},select=0"
        )
    for region in policies["regions"]:
        region_filter = filters["regions"][region["name"]]
        lines.append(
            f"{region['auto_name']} = url-test,url={benchmark['url']},"
            f"interval={benchmark['interval']},tolerance={benchmark['tolerance']},"
            f"timeout={benchmark['timeout']},select=0,"
            f"policy-regex-filter={region_filter}"
        )
        lines.append(
            f"{region['manual_name']} = select,"
            f"url={benchmark['url']},interval={benchmark['interval']},"
            f"timeout={benchmark['timeout']},select=0,"
            f"policy-regex-filter={region_filter}"
        )

    lines.extend(["", "# Ordered remote rules; the first match wins.", "[Rule]"])
    for entry in policies["_compiled_rulesets"]:
        url = f"{raw_base}/dist/shadowrocket/rules/{entry.id}.list"
        lines.append(f"RULE-SET,{url},{entry.policy}")
    lines.extend(["GEOIP,CN,DIRECT", "FINAL,Final"])
    return "\n".join(lines) + "\n"


def _surge_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    updates = project["updates"]
    filters = build_filters(policies)
    lines = [
        PROFILE_HEADER.rstrip(), LOCAL_PROFILE_NOTICE.rstrip(), SERVICE_GROUP_NOTICE.rstrip(), "",
        "[General]", "loglevel = notify", "ipv6 = false",
        "allow-wifi-access = false", "dns-server = system",
        f"proxy-test-url = {benchmark['url']}",
        f"test-timeout = {benchmark['timeout']}", "", "[Proxy]", "",
        "[Proxy Group]",
        "# 在 policy-path 填写 Surge 格式节点订阅；第一份默认启用，订阅组在策略界面隐藏。",
        f"Subscription1 = select,policy-path={SUBSCRIPTION_PLACEHOLDER},"
        f"update-interval={updates['node_interval']},hidden=true",
        f"# Subscription2 = select,policy-path={SUBSCRIPTION_PLACEHOLDER},"
        f"update-interval={updates['node_interval']},hidden=true",
        "",
        '# 多订阅：取消 Subscription2 注释并填写，再将下方引用改为 include-other-group="Subscription1,Subscription2"。',
        "# 更多订阅复制订阅行、名称递增，并逐一加入该引用列表；Manual 展开所有已引用订阅的节点。",
        "Manual = select,include-other-group=Subscription1,include-all-proxies=true",
    ]
    # icon-url is currently documented as Mac-only; omit it for an iOS-safe profile.
    for service in policies["service_groups"]:
        lines.append(f"{service} = select,{','.join(policies['service_options'])}")
    lines.append("# 地区组展开 Manual 中的全部节点，再做正向筛选，不跟随其单个选中节点。")
    for region in policies["regions"]:
        suffix = f'include-other-group=Manual,policy-regex-filter="{filters["regions"][region["name"]]}"'
        lines.append(
            f"{region['auto_name']} = url-test,{suffix},"
            f"interval={benchmark['interval']},tolerance={benchmark['tolerance']}"
        )
        lines.append(f"{region['manual_name']} = select,{suffix}")
    lines.extend(["", "# Ordered remote routing rules.", "[Rule]"])
    for entry in policies["_compiled_rulesets"]:
        lines.append(f"RULE-SET,{_rule_url(project, 'surge', entry.id)},{entry.policy},"
                     f"update-interval={updates['rule_interval']}")
    lines.extend(["GEOIP,CN,DIRECT", "FINAL,Final"])
    return "\n".join(lines) + "\n"


def _qx_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    updates = project["updates"]
    filters = build_filters(policies)

    def icon(name: str) -> str:
        url = _icon(icons, name)
        return f", img-url={url}" if url else ""

    lines = [
        PROFILE_HEADER.rstrip(), LOCAL_PROFILE_NOTICE.rstrip(), SERVICE_GROUP_NOTICE.rstrip(),
        "# 订阅填写位置在下方 [server_remote]。", "",
        "[general]", f"server_check_url = {benchmark['url']}",
        f"server_check_timeout = {min(5000, benchmark['timeout'] * 1000)}",
        "", "[dns]", "no-ipv6", "server = system", "",
        "[policy]", f"static = Manual, server-tag-regex=.+{icon('Manual')}",
    ]
    options = ", ".join(_qx_policy(option) for option in policies["service_options"])
    for service in policies["service_groups"]:
        lines.append(f"static = {service}, {options}{icon(service)}")
    for region in policies["regions"]:
        expression = filters["regions"][region["name"]]
        lines.append(
            f"url-latency-benchmark = {region['auto_name']}, server-tag-regex={expression}, "
            f"check-interval={benchmark['interval']}, alive-checking=false, "
            f"tolerance={benchmark['tolerance']}{icon(region['name'])}"
        )
        lines.append(f"static = {region['manual_name']}, server-tag-regex={expression}"
                     f"{icon(region['name'])}")
    lines.extend([
        "", "[server_remote]", "# 填写 Quantumult X 格式节点订阅；第一份默认启用。",
        "# 多订阅：取消第二行注释并填写；更多订阅复制该行并使用不同 tag。",
        f"{SUBSCRIPTION_PLACEHOLDER}, tag=Subscription1, update-interval={updates['node_interval']}, enabled=true",
        f"# {SUBSCRIPTION_PLACEHOLDER}, tag=Subscription2, update-interval={updates['node_interval']}, enabled=true",
        "", "[server_local]", "", "[filter_remote]",
        "# 不导入客户端默认 CN/LAN 资源，避免抢先覆盖本项目的服务分流。",
    ])
    for entry in policies["_compiled_rulesets"]:
        lines.append(
            f"{_rule_url(project, 'qx', entry.id)}, tag={entry.id}, "
            f"force-policy={_qx_policy(entry.policy)}, update-interval={updates['rule_interval']}, "
            "enabled=true"
        )
    lines.extend(["", "[filter_local]", "geoip,cn,direct", "final,Final"])
    return "\n".join(lines) + "\n"


def _egern_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    updates = project["updates"]
    filters = build_filters(policies)
    groups = [{"select": _with_icon({
        "name": "Manual", "urls": [SUBSCRIPTION_PLACEHOLDER],
        "update_interval": updates["node_interval"],
    }, icons, "Manual")}]
    for service in policies["service_groups"]:
        groups.append({"select": _with_icon({
            "name": service, "policies": list(policies["service_options"]),
        }, icons, service)})
    for region in policies["regions"]:
        for kind, name in (("auto_test", region["auto_name"]), ("select", region["manual_name"])):
            group = {
                "name": name, "policies": ["Manual"], "flatten": True,
                "filter": filters["regions"][region["name"]],
            }
            if kind == "auto_test":
                group.update(interval=benchmark["interval"], tolerance=benchmark["tolerance"],
                             timeout=benchmark["timeout"])
            groups.append({kind: _with_icon(group, icons, region["name"])})
    rules = [{"rule_set": {
        "match": _rule_url(project, "egern", entry.id), "policy": entry.policy,
        "update_interval": updates["rule_interval"],
    }} for entry in policies["_compiled_rulesets"]]
    rules.extend([{"geoip": {"match": "CN", "policy": "DIRECT"}},
                  {"default": {"policy": "Final"}}])
    data = {
        "ipv6": False, "allow_external_connections": False,
        "proxy_latency_test_url": benchmark["url"],
        "dns": {"bootstrap": ["system"],
                "forward": [{"wildcard": {"match": "*", "value": "bootstrap"}}]},
        "policy_groups": groups, "rules": rules,
    }
    body = _yaml(data).replace(
        "policy_groups:\n", "# 在 Manual 的 urls 中填写 Egern 支持的节点订阅；第一份默认启用。\npolicy_groups:\n", 1
    )
    body = body.replace(
        f"    - {SUBSCRIPTION_PLACEHOLDER}\n",
        f"    - {SUBSCRIPTION_PLACEHOLDER}\n"
        "    # 多订阅：取消下一行注释并填写；更多地址在 urls 中逐行追加，保留缩进。\n"
        f"    # - {SUBSCRIPTION_PLACEHOLDER}\n",
        1,
    )
    return PROFILE_HEADER + LOCAL_PROFILE_NOTICE + SERVICE_GROUP_NOTICE + "\n" + body


def render_all(
    root: Path,
    project: dict[str, Any],
    policies: dict[str, Any],
    icons: dict[str, Any],
    rulesets: list[CompiledRuleset],
) -> dict[str, Any]:
    dist = root / "dist"
    render_policies = dict(policies)
    render_policies["_compiled_rulesets"] = rulesets
    skipped: dict[str, dict[str, int]] = {target: {} for target in TARGETS}
    expected: dict[str, set[Path]] = {target: set() for target in TARGETS}
    for target in TARGETS:
        for ruleset in rulesets:
            rendered: list[str] = []
            skipped_count = 0
            if target == "egern":
                content = render_egern_ruleset(ruleset)
            else:
                for rule in ruleset.rules:
                    line = render_rule(rule, target, ruleset.no_resolve, ruleset.policy)
                    if line is None:
                        skipped_count += 1
                    else:
                        rendered.append(line)
                content = _ruleset_header(ruleset) + "\n".join(rendered) + "\n"
            path = dist / target / "rules" / rule_filename(target, ruleset.id)
            expected[target].add(path)
            write_if_changed(path, content)
            if skipped_count:
                skipped[target][ruleset.id] = skipped_count

        rules_dir = dist / target / "rules"
        if rules_dir.exists():
            for stale in rules_dir.iterdir():
                if not stale.is_file() or stale.suffix not in {".list", ".yaml"}:
                    continue
                if stale not in expected[target]:
                    stale.unlink()

    renderers = {
        "stash": _stash_config, "loon": _loon_config, "surge": _surge_config,
        "qx": _qx_config, "egern": _egern_config,
    }
    for target in TARGETS:
        content = (_shadowrocket_config(project, render_policies) if target == "shadowrocket"
                   else renderers[target](project, render_policies, icons))
        path = dist / target / CONFIG_FILENAMES[target]
        write_if_changed(path, _with_stable_update_time(path, content))
    return {
        "schema": 1,
        "unsupported_rules": skipped,
        "notes": {
            "stash": "DOMAIN-REGEX is retained.",
            "loon": "DOMAIN-REGEX is omitted because Loon remote rules do not support it.",
            "shadowrocket": "DOMAIN-REGEX is omitted for compatibility.",
            "surge": "DOMAIN-REGEX is unsupported and omitted. Native url-test groups allow temporary manual override; icons are omitted for iOS compatibility.",
            "qx": "Native host/ip rules with explicit policies. DOMAIN-REGEX is omitted; Surge-style no-resolve is not emitted. QX uses native domain/IP matching priorities.",
            "egern": "Native YAML rule sets preserve domain regex and no_resolve. Requires a current Egern release with urls and flatten support.",
        },
    }
