from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

import yaml

from .compiler import CompiledRuleset
from .filters import build_filters
from .model import Rule


TARGETS = ("stash", "loon", "shadowrocket")
GENERATED_HEADER = "# Generated by ProxyRules. Do not edit this file directly.\n"
UPDATE_TIME_PREFIX = "# Last updated: "
UPDATE_TIME_PATTERN = re.compile(r"^# Last updated: .*\n?", re.MULTILINE)
UPDATE_TIMEZONE = ZoneInfo("Asia/Shanghai")


def write_if_changed(path: Path, content: str) -> bool:
    """Write a UTF-8 text file only when its contents changed."""

    if not content.endswith("\n"):
        content += "\n"
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def write_json_if_changed(path: Path, value: Any) -> bool:
    return write_if_changed(
        path,
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
    )


def _without_update_time(content: str) -> str:
    return UPDATE_TIME_PATTERN.sub("", content, count=1)


def _with_stable_update_time(path: Path, content: str) -> str:
    """Add an update time, preserving the old one when generated content is unchanged."""

    if not content.endswith("\n"):
        content += "\n"
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if _without_update_time(existing) == _without_update_time(content):
            return existing

    timestamp = datetime.now(UPDATE_TIMEZONE).strftime(
        "%Y-%m-%d %H:%M:%S (Asia/Shanghai)"
    )
    first_line, remainder = content.split("\n", 1)
    return f"{first_line}\n{UPDATE_TIME_PREFIX}{timestamp}\n{remainder}"


def render_rule(rule: Rule, target: str, no_resolve: bool = False) -> str | None:
    kinds = {
        "full": "DOMAIN",
        "domain": "DOMAIN-SUFFIX",
        "keyword": "DOMAIN-KEYWORD",
        "regexp": "DOMAIN-REGEX",
        "ipcidr": "IP-CIDR",
        "ipcidr6": "IP-CIDR6",
    }
    if target not in TARGETS:
        raise ValueError(f"Unknown target: {target}")
    if rule.kind == "regexp" and target != "stash":
        return None
    if rule.kind not in kinds:
        return None
    parts = [kinds[rule.kind], rule.value]
    if no_resolve and rule.kind in {"ipcidr", "ipcidr6"}:
        parts.append("no-resolve")
    return ",".join(parts)


def _icon(icons: dict[str, Any], name: str) -> str | None:
    filename = icons.get("icons", {}).get(name)
    if not filename:
        return None
    return f"{icons['base'].rstrip('/')}/{filename}"


def _with_icon(group: dict[str, Any], icons: dict[str, Any], name: str) -> dict[str, Any]:
    if url := _icon(icons, name):
        group["icon"] = url
    return group


def _stash_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    project_settings = project["project"]
    benchmark = project["benchmark"]
    update_settings = project["updates"]
    raw_base = project_settings["raw_base"].rstrip("/")
    filters = build_filters(policies)

    groups: list[dict[str, Any]] = []
    groups.append(
        _with_icon(
            {
                "name": "Manual",
                "type": "select",
                "include-all": True,
            },
            icons,
            "Manual",
        )
    )

    for service in policies["service_groups"]:
        groups.append(
            _with_icon(
                {
                    "name": service,
                    "type": "select",
                    "proxies": list(policies["service_options"]),
                },
                icons,
                service,
            )
        )

    for region in policies["regions"]:
        region_filter = filters["regions"][region["name"]]
        groups.append(
            _with_icon(
                {
                    "name": region["auto_name"],
                    "type": "url-test",
                    "include-all": True,
                    "filter": region_filter,
                    "interval": benchmark["interval"],
                    "tolerance": benchmark["tolerance"],
                    "lazy": benchmark["lazy"],
                },
                icons,
                region["name"],
            )
        )
        groups.append(
            _with_icon(
                {
                    "name": region["manual_name"],
                    "type": "select",
                    "include-all": True,
                    "filter": region_filter,
                },
                icons,
                region["name"],
            )
        )

    providers: dict[str, dict[str, Any]] = {}
    route_rules: list[str] = []
    for entry in policies["_compiled_rulesets"]:
        providers[entry.id] = {
            "type": "http",
            "behavior": "classical",
            "format": "text",
            "url": f"{raw_base}/dist/stash/rules/{entry.id}.list",
            "path": f"./rulesets/{entry.id}.list",
            "interval": update_settings["rule_interval"],
        }
        route_rules.append(f"RULE-SET,{entry.id},{entry.policy}")
    route_rules.extend(["GEOIP,CN,DIRECT", "MATCH,Final"])

    data = {
        "mode": "rule",
        "log-level": "warning",
        "ipv6": False,
        "proxy-groups": groups,
        "rule-providers": providers,
        "rules": route_rules,
    }
    body = yaml.safe_dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        width=4096,
        default_flow_style=False,
    )
    body = body.replace(
        "proxy-groups:\n",
        "# Base, service, and region strategy groups.\nproxy-groups:\n",
        1,
    )
    body = body.replace(
        "rule-providers:\n",
        "# Remote rule files generated from the shared manifest.\nrule-providers:\n",
        1,
    )
    body = body.replace(
        "rules:\n",
        "# Rules are evaluated from top to bottom.\nrules:\n",
        1,
    )
    return (
        GENERATED_HEADER
        + "# 添加节点订阅：「设置」→「配置文件」→选中本配置→「可视化编辑」→「远程代理集」→右上角「+」。\n"
        + body
    )


def _loon_group(
    name: str,
    group_type: str,
    members: list[str],
    benchmark: dict[str, Any],
    icon_url: str | None,
    *,
    automated: bool = False,
) -> str:
    parts = [f"{name} = {group_type}", *members]
    if automated:
        parts.append(f"url = {benchmark['url']}")
        parts.append(f"interval = {benchmark['interval']}")
        if group_type == "url-test":
            parts.append(f"tolerance = {benchmark['tolerance']}")
    if icon_url:
        parts.append(f"img-url = {icon_url}")
    return ",".join(parts)


def _loon_config(
    project: dict[str, Any], policies: dict[str, Any], icons: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    raw_base = project["project"]["raw_base"].rstrip("/")
    filters = build_filters(policies)
    lines = [
        GENERATED_HEADER.rstrip(),
        "",
        "[General]",
        "ipv6 = false",
        "allow-wifi-access = false",
        f"proxy-test-url = {benchmark['url']}",
        f"test-timeout = {benchmark['timeout']}",
        "",
        "[Proxy]",
        "",
        "# 添加节点订阅：「配置」→「节点」→右上角「+」→「添加订阅」。",
        "[Remote Proxy]",
        "",
        "# Node and region filters.",
        "[Remote Filter]",
        f'Manual Nodes = NameRegex, FilterKey = "{filters["manual"]}"',
    ]
    for region in policies["regions"]:
        code = region["code"]
        region_filter = filters["regions"][region["name"]]
        lines.append(f'{code} Nodes = NameRegex, FilterKey = "{region_filter}"')

    lines.extend(["", "# Base, service, and region strategy groups.", "[Proxy Group]"])
    lines.append(
        _loon_group(
            "Manual",
            "select",
            ["Manual Nodes"],
            benchmark,
            _icon(icons, "Manual"),
        )
    )
    for service in policies["service_groups"]:
        lines.append(
            _loon_group(
                service,
                "select",
                list(policies["service_options"]),
                benchmark,
                _icon(icons, service),
            )
        )
    for region in policies["regions"]:
        code = region["code"]
        lines.append(
            _loon_group(
                region["auto_name"],
                "url-test",
                [f"{code} Nodes"],
                benchmark,
                _icon(icons, region["name"]),
                automated=True,
            )
        )
        lines.append(
            _loon_group(
                region["manual_name"],
                "select",
                [f"{code} Nodes"],
                benchmark,
                _icon(icons, region["name"]),
            )
        )

    lines.extend(["", "# Ordered remote routing rules.", "[Remote Rule]"])
    for entry in policies["_compiled_rulesets"]:
        url = f"{raw_base}/dist/loon/rules/{entry.id}.list"
        lines.append(
            f"{url}, policy = {entry.policy}, tag = {entry.title}, enabled = true"
        )
    lines.extend(
        ["", "# Local fallback rules.", "[Rule]", "GEOIP,CN,DIRECT", "FINAL,Final"]
    )
    return "\n".join(lines) + "\n"


def _shadowrocket_config(
    project: dict[str, Any], policies: dict[str, Any]
) -> str:
    benchmark = project["benchmark"]
    raw_base = project["project"]["raw_base"].rstrip("/")
    filters = build_filters(policies)
    config_url = f"{raw_base}/dist/shadowrocket/shadowrocket.conf"
    lines = [
        GENERATED_HEADER.rstrip(),
        "",
        "[General]",
        "ipv6 = false",
        f"proxy-test-url = {benchmark['url']}",
        f"test-timeout = {benchmark['timeout']}",
        "# Remote URL used to refresh this configuration.",
        f"update-url = {config_url}",
        "",
        "# Base, service, and region strategy groups.",
        "[Proxy Group]",
        (
            "Manual = select,"
            f"url={benchmark['url']},interval={benchmark['interval']},"
            f"timeout={benchmark['timeout']},select=0,"
            f"policy-regex-filter={filters['manual']}"
        ),
    ]
    for service in policies["service_groups"]:
        members = ",".join(policies["service_options"])
        lines.append(
            f"{service} = select,{members},url={benchmark['url']},"
            f"interval={benchmark['interval']},timeout={benchmark['timeout']},select=0"
        )
    for region in policies["regions"]:
        region_filter = filters["regions"][region["name"]]
        lines.append(
            f"{region['auto_name']} = url-test,url={benchmark['url']},"
            f"interval={benchmark['interval']},tolerance={benchmark['tolerance']},"
            f"timeout={benchmark['timeout']},select=0,"
            f"policy-regex-filter={region_filter}"
        )
        lines.append(
            f"{region['manual_name']} = select,"
            f"url={benchmark['url']},interval={benchmark['interval']},"
            f"timeout={benchmark['timeout']},select=0,"
            f"policy-regex-filter={region_filter}"
        )

    lines.extend(["", "# Ordered remote rules; the first match wins.", "[Rule]"])
    for entry in policies["_compiled_rulesets"]:
        url = f"{raw_base}/dist/shadowrocket/rules/{entry.id}.list"
        lines.append(f"RULE-SET,{url},{entry.policy}")
    lines.extend(["GEOIP,CN,DIRECT", "FINAL,Final"])
    return "\n".join(lines) + "\n"


def render_all(
    root: Path,
    project: dict[str, Any],
    policies: dict[str, Any],
    icons: dict[str, Any],
    rulesets: list[CompiledRuleset],
) -> dict[str, Any]:
    dist = root / "dist"
    render_policies = dict(policies)
    render_policies["_compiled_rulesets"] = rulesets
    skipped: dict[str, dict[str, int]] = {target: {} for target in TARGETS}
    expected: dict[str, set[Path]] = {target: set() for target in TARGETS}
    for target in TARGETS:
        for ruleset in rulesets:
            rendered: list[str] = []
            skipped_count = 0
            for rule in ruleset.rules:
                line = render_rule(rule, target, ruleset.no_resolve)
                if line is None:
                    skipped_count += 1
                else:
                    rendered.append(line)
            path = dist / target / "rules" / f"{ruleset.id}.list"
            expected[target].add(path)
            content = GENERATED_HEADER + "\n".join(rendered) + "\n"
            write_if_changed(path, content)
            if skipped_count:
                skipped[target][ruleset.id] = skipped_count

        rules_dir = dist / target / "rules"
        if rules_dir.exists():
            for stale in rules_dir.glob("*.list"):
                if stale not in expected[target]:
                    stale.unlink()

    main_configs = {
        dist / "stash" / "stash.yaml": _stash_config(
            project, render_policies, icons
        ),
        dist / "loon" / "loon.conf": _loon_config(
            project, render_policies, icons
        ),
        dist / "shadowrocket" / "shadowrocket.conf": _shadowrocket_config(
            project, render_policies
        ),
    }
    for path, content in main_configs.items():
        write_if_changed(path, _with_stable_update_time(path, content))
    return {
        "schema": 1,
        "unsupported_rules": skipped,
        "notes": {
            "stash": "DOMAIN-REGEX is retained.",
            "loon": "DOMAIN-REGEX is omitted because Loon remote rules do not support it.",
            "shadowrocket": "DOMAIN-REGEX is omitted for compatibility.",
        },
    }
